const { Server} = require('./core')
const {UtilisateurRoutes} = require('./services/moduleUser/routes')
const {AdminRoutes} = require('./services/moduleAdmin/routes')
const {TypepostRoutes} = require('./services/moduleTypepost/routes')
const {CategorieRoutes} = require('./services/moduleCategorie/routes')
const {PostRoutes} = require('./services/modulePost/routes')
const {ImageRoutes} = require('./services/moduleImage/routes')
require('./utils/config')

const server = new Server
server.handle400()
      .setRoutes(UtilisateurRoutes)
      .setRoutes(AdminRoutes)
      .setRoutes(TypepostRoutes)
      .setRoutes(CategorieRoutes)
      .setRoutes(PostRoutes)
      .setRoutes(ImageRoutes)
      .handle404()
      .startServer()